### ISSUE TITLE
Bug: Week Number is Off by One

### ISSUE THREAD

**Issue by tak0407** [bartkessels/daily-note-calendar#94]
![Image](https://github.com/user-attachments/assets/e2d356d4-2482-4a22-b071-9872cdcb34e8)

Describe the bug
When the start of the week is set to Sunday, the displayed week number is off by one.
For example, this week is supposed to be Week 14, but the plugin shows it as Week 13.

(I’m just a regular Obsidian user and a big fan of this plugin — thank you so much for making it! This is actually my first time reporting a bug on GitHub, so I hope the report is helpful. 🙏)

**Comment by bartkessels** [comment]
Hello, thanks for reporting this issue.

I've been able to reproduce it (pretty easy) and have a fix for it. It'll be fixed in version 2.0.2 that will be released in a couple of minutes.

As always, thanks for your feedback and if you have any issue or a feature request feel free to let me know.

**Comment by bartkessels** [comment]
Version 2.0.2 has just been released, once you've updated the plugin your issue should be resolved.

**Comment by coddingtonbear** [comment]
Forgive me, I think I'm using the latest version of this plugin, and I believe I still see this issue:

![Image](https://github.com/user-attachments/assets/d24f82ad-fcf4-4163-bc2c-d291079ab7c5)

![Image](https://github.com/user-attachments/assets/4992e812-be4e-46e5-a253-1914bb943b85)

For what it's worth, I'd be glad to help investigate this personally later this weekend if you needed a hand.

**Comment by bartkessels** [comment]
Hello, I've been testing this on my own machine and checking the data with the installed calendar app on my laptop and could not find the issue you're having. That was until issue #99 was opened.

Apparently there are two standards for defining week numbers, US (the one you are using) and ISO (the one the plugin uses). I never knew that there was a difference between week numbers, but the world of time always has its quirks. However, I'll be adding a setting which allows you to choose what standard you'd like to use for the plugin in the next release. That wil fix this issue, for good this time 😜.

Again, thanks for using this plugin and your patience! And if you encounter any other bugs, or have feature requests feel free to let me know! (I'll be opening this issue again until the release has been made available)

**Comment by bartkessels** [comment]
Version 2.2.0 that addresses this bug has just been released!
